= Vert.x Circuit Breaker

Vert.x Circuit Breaker is an implementation of the _circuit breaker_ pattern for Vert.x. It keeps track of the
number of recent failures and prevents further executions when a threshold is reached. Optionally, a fallback is executed.

Supported failures are:

* failures reported by your code in a {@link io.vertx.core.Future}
* exception thrown by your code
* uncompleted futures (timeout)

Operations guarded by a circuit breaker are intended to be non-blocking and asynchronous in order to benefit from
the Vert.x execution model.

== Using Vert.x Circuit Breaker

To use Vert.x Circuit Breaker, add the following dependency to the _dependencies_ section of your build
descriptor:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-circuit-breaker</artifactId>
  <version>${maven.version}</version>
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
compile 'io.vertx:vertx-circuit-breaker:${maven.version}'
----

== Using the circuit breaker

To use the circuit breaker you need to:

1. Create a circuit breaker, with the configuration you want (timeout, failure threshold)
2. Execute some code using the circuit breaker

**Important**: Don't recreate a circuit breaker on every call. A circuit breaker is a stateful entity. It is recommended
to store the circuit breaker instance in a field.

Here is an example:

[source,$lang]
----
{@link examples.CircuitBreakerExamples#example1(io.vertx.core.Vertx)}
----

The executed block receives a {@link io.vertx.core.Promise} object as parameter, to denote the
success or failure of the operation as well as the result. In the following example, the result is the
output of a REST endpoint invocation:

[source,$lang]
----
{@link examples.CircuitBreakerExamples#example2(io.vertx.core.Vertx)}
----

The result of the operation is provided using the:

* returned {@link io.vertx.core.Future} when calling `execute` methods
* provided {@link io.vertx.core.Promise} when calling the `executeAndReport` methods

Optionally, you can provide a fallback which is executed when the circuit breaker is open:

[source,$lang]
----
{@link examples.CircuitBreakerExamples#example3(io.vertx.core.Vertx)}
----

The fallback is called when the circuit breaker is open, or when
{@link io.vertx.circuitbreaker.CircuitBreakerOptions#isFallbackOnFailure()} is enabled. When fallback is
set, the overall result is obtained by calling the fallback function. The fallback function takes as parameter a
{@link java.lang.Throwable} object and returns an object of the expected type.

The fallback can also be set on the {@link io.vertx.circuitbreaker.CircuitBreaker} object directly:

[source,$lang]
----
{@link examples.CircuitBreakerExamples#example4(io.vertx.core.Vertx)}
----

=== Reported exceptions

The fallback receives:

* {@link io.vertx.circuitbreaker.OpenCircuitException} when the circuit breaker is open
* {@link io.vertx.circuitbreaker.TimeoutException} when the operation timed out

== Retries

You can also specify how often the circuit breaker should execute your code before failing with {@link io.vertx.circuitbreaker.CircuitBreakerOptions#setMaxRetries(int)}.
If you set this to something higher than 0, your code gets executed several times before finally failing in the last execution.
If the code succeeds in one of the retries, your handler gets notified and no more retries occur.
Retries are only supported when the circuit breaker is closed.

NOTE: If you set `maxRetries` to 2, your operation may be called 3 times: the initial attempt and 2 retries.

By default, the delay between retries is set to 0, which means that retries will be executed one after another immediately.
This, however, will result in increased load on the called service and may delay its recovery.
In order to mitigate this problem, it is recommended to execute retries with a delay.

The {@link io.vertx.circuitbreaker.CircuitBreaker#retryPolicy(io.vertx.circuitbreaker.RetryPolicy)} method can be used to specify a retry policy.
A retry policy is a function which receives the operation failure and retry count as arguments and returns a delay in milliseconds before retry should be executed.

It allows to implement complex policies, e.g. using the value of the https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After[`Retry-After`] header sent by an unavailable service.
Some common policies are provided out of the box: {@link io.vertx.circuitbreaker.RetryPolicy#constantDelay}, {@link io.vertx.circuitbreaker.RetryPolicy#linearDelay} and {@link io.vertx.circuitbreaker.RetryPolicy#exponentialDelayWithJitter}

Below is an example of exponential delay with jitter:

[source,$lang]
----
{@link examples.CircuitBreakerExamples#example8(io.vertx.core.Vertx)}
----

== Callbacks

You can also configure callbacks invoked when the circuit breaker is opened or closed:

[source,$lang]
----
{@link examples.CircuitBreakerExamples#example5(io.vertx.core.Vertx)}
----

You can also be notified when the circuit breaker moves to the half-open state, in an attempt to reset. You can register
such a callback with {@link io.vertx.circuitbreaker.CircuitBreaker#halfOpenHandler(io.vertx.core.Handler)}.

== Event bus notification

Every time the circuit breaker state changes, an event can be published on the event bus.

To enable this feature, set the {@link io.vertx.circuitbreaker.CircuitBreakerOptions#setNotificationAddress(java.lang.String) notification address} to a value that is not `null`:

[source,$lang]
----
{@link examples.CircuitBreakerExamples#enableNotifications}
----

The event contains circuit breaker metrics.
Computing these metrics requires the following dependency to be added the _dependencies_ section of your build descriptor:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>org.hdrhistogram</groupId>
  <artifactId>HdrHistogram</artifactId>
  <version>2.1.12</version>
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
compile 'org.hdrhistogram:HdrHistogram:2.1.12'
----

[NOTE]
====
When enabled, notifications are delivered only to local consumers by default.
If the notification must be sent to all consumers in a cluster, you can change this behavior with {@link io.vertx.circuitbreaker.CircuitBreakerOptions#setNotificationLocalOnly}.
====

Each event contains a Json Object with:

* `state`: the new circuit breaker state (`OPEN`, `CLOSED`, `HALF_OPEN`)
* `name`: the name of the circuit breaker
* `failures`: the number of failures
* `node`: the identifier of the node (`local` if Vert.x is not running in cluster mode)
* metrics

== The half-open state

When the circuit breaker is `open`, calls to the circuit breaker fail immediately, without any attempt to execute the real
operation. After a suitable amount of time (configured by
{@link io.vertx.circuitbreaker.CircuitBreakerOptions#setResetTimeout(long)}), the circuit breaker decides that the
operation has a chance of succeeding, so it goes into the `half-open` state. In this state, the next call to the
circuit breaker is allowed to execute the guarded operation. Should the call succeed, the circuit breaker resets
and returns to the `closed` state, ready for more routine operation. If this trial call fails, however, the circuit
breaker returns to the `open` state until another timeout elapses.
